CHANGES.rst, docs/development.rst, plone/app/event/dx/behaviors.py, plone/app/event/dx/configure.zcml, plone/app/event/tests/base_setup.py, plone/app/event/tests/test_base_module.py, plone/app/event/tests/test_dx_behaviors.py
Remove ``data_postprocessing`` logic, which was handling ``open_end`` and
``whole_day`` events and was manipulating the object on form submission.
Instead, just adapt start/end dates on indexing and when accessing them via
``IEventAccessor``.
RFC: @jensens @regebro @zopyx @davisagli 
should be safe and backwards-compatible, except that people will have to stop using data_postprocessing, if they do.
=> Remove data_postprocessing

CHANGES.rst, plone/app/event/bbb/portlets/portlet_events.pt, plone/app/event/portlets/portlet_events.pt
Location already has a CSS class and sometimes hiding the timezone makes the list of events neater.
=> CSS class for the timezone in portlet_events.pt

CHANGES.rst, plone/app/event/bbb/portlets/portlet_events.pt, plone/app/event/browser/event_listing.pt, plone/app/event/browser/event_listing.py, plone/app/event/browser/event_summary.pt, plone/app/event/browser/event_summary.py, plone/app/event/browser/event_view.py, plone/app/event/ical/importer.py, plone/app/event/portlets/portlet_events.pt, plone/app/event/portlets/portlet_events.py, plone/app/event/tests/test_event_summary.py
Remove ``get_location`` view helper method. This was used to allow external addons (specifically ``collective.venue``) to override it and return a html link to a location object instead. Instead of this hack, which also only works for the location use case, override the necessary templates in your addons. In case of doubt, simplicity outweight extensibility options.
=> remove get_location view helper

CHANGES.rst, plone/app/event/browser/configure.zcml, plone/app/event/browser/leadimage_viewlet.py, plone/app/event/recurrence.py, plone/app/event/tests/test_recurrence.py
- Fix ``ImageScalingViewFactory`` and add a custom ILeadImage viewlet for Occurrences. Fixes the display of ILeadImage images from the originating event in event views of occurrences by delegating to the parent object.
- Fix Plone 4.3 BBB z3c.form portlets to show their fields in Add/Edit Forms.
=> ImageScalingViewFactory and ILeadImage viewlet customization for Occurrences

CHANGES.rst, plone/app/event/browser/event_listing.py
This allows the contentFilter dictionary on a request to narrow down listings
=> Support for contentFilter on request for event_listing.

CHANGES.rst, plone/app/event/browser/event_listing.py, plone/app/event/portlets/portlet_calendar.py, plone/app/event/portlets/portlet_events.py
Extend Collection support on ``event_listing`` for content items providing ``ISyndicatableCollection``.
For ``event_listing`` on Collections, ignore the Collection's sorting and use  what the event listing's mode defines for sorting.
Add support for Collections as data source for calendar and event portlets.
=> more collection improvements

CHANGES.rst, plone/app/event/portlets/portlet_calendar.py, plone/app/event/portlets/portlet_events.py
Unwrap search_base for portlets, as it might be wrapped by the portlet renderer class. Fixes an error with getting the events to display.
=> unwrap search_base in portlets

CHANGES.rst, plone/app/event/base.py, plone/app/event/browser/event_listing.py, plone/app/event/tests/test_base_module.py
Remove inconsistency in date_speller and rename ``month`` and ``wkday`` keys
to ``month_name`` and ``wkday_name``. Introduce ``month``, the non-zero
padded numeric value of the current month, ``month2``, the zero-padded one,
``wkday``, the weekday number and ``week``, the weeknumber of the current
year.
=> date speller changes

CHANGES.rst, plone/app/event/browser/resources/event.js, plone/app/event/portlets/portlet_calendar.py, plone/app/event/portlets/portlet_events.py
after some time back to plone development :)
plone 4.3. i'm only want to use p.a.event without p.a.contenttypes. it is an addon and there is no need to depend on p.a.contenttypes.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/plone/plone.app.event/195)
=> removing dependency on p.a.contenttypes

CHANGES.rst, plone/app/event/tests/base_setup.py, plone/app/event/tests/test_base_module.py, plone/app/event/tests/test_catalog.py, plone/app/event/tests/test_dx_behaviors.py, plone/app/event/tests/test_icalendar.py, plone/app/event/tests/test_portlet_calendar.py, plone/app/event/tests/test_portlet_events.py, plone/app/event/tests/test_recurrence.py, setup.py
Since python 2.7 unittest2 was already merged with unittest.
=> No need for unittest2

README.rst
Fixes https://github.com/plone/plone.app.event/issues/179
@svx do we host that documentation somewhere on docs.plone.org? Should I open a ticket for it? @thet any reason not to move the docs to docs.plone.org?
=> Point to documentation

CHANGES.rst, plone/app/event/base.py, plone/app/event/browser/formatted_date.py
Don't break ``base.dates_for_display`` and the ``formatted_date`` content provider, if event object has no start or end dates.
It might come from a potential event.
=> More graceful dates_for_display when no start/end

CHANGES.rst, plone/app/event/dx/behaviors.py, plone/app/event/tests/test_dx_behaviors.py
Don't validate the ``validate_start_end`` invariant, if start or end are ``None``.
This can happen on non-required, default empty start or end fields during editing.
=> Don't validate empty start/end

CHANGES.rst, plone/app/event/browser/resources/event.js, plone/app/event/dx/behaviors.py, plone/app/event/dx/configure.zcml, setup.py
- Make use of more generic selectors in JavaScript, so that JavaScript works also for derived classes.
- Configure custom css classes for all event behavior fields.
This makes it easier to use same selectors also for derived behaviors.
- Use ``plone.autoform.directives`` for manipulating field widgets instead of overriding the default Fieldwidget adapters.
=> plone.autoform.directives and more generic javascript

CHANGES.rst, plone/app/event/browser/event_listing.pt, plone/app/event/browser/event_summary.pt, plone/app/event/portlets/portlet_events.pt
Note if you had custom code to override the get_location view helper method to return html, this no longer works.  For plain text it still works fine, but the get_location method is gone in version
2.0, for simplicity.  Instead you can override the necessary templates in your addons.
=> Fixed possible XSS attack in location field. [1.1]

CHANGES.rst, plone/app/event/dx/behaviors.py
Some behavior notify IObjectModifiedEvent, and event is not created when this notify is called, 
So event UUID has not yet been assigned and we have a TypeError.
Now we check if UUID is assigned
=> Fix bug when an event is in creation and has not yet uid.

CHANGES.rst, plone/app/event/dx/behaviors.py
Do not index sync_uid, start and end fields if they are empty.
With ZCatalog >= 3.1, None index value are not allowed
=> Do not index sync_uid, start and end fields if they are empty.

plone/app/event/locales/nl/LC_MESSAGES/plone.app.event.po
There is a mistake in the msgid "msg_num_more_occurrences":
“Er zijn nog ${resuls} andere momenten.”
It should be:
“Er zijn nog ${results} andere momenten.”
=> Fixed dutch translations

CHANGES.rst, plone/app/event/dx/behaviors.py, plone/app/event/locales/fr/LC_MESSAGES/plone.app.event.po
- Update french translations.
- Do not index `sync_uid`, `start` and `end` fields if they are empty.
=> bsuttor cherry picks from 1.1.x into 2.0 branch

CHANGES.rst, plone/app/event/portlets/portlet_calendar.py, plone/app/event/tests/test_portlet_calendar.py
https://github.com/plone/Products.CMFPlone/issues/1046 
@thet: afaik,  events_string  is not used anywhere else (?)
=> fix format of tooltip in calendar portlet 

CHANGES.rst, plone/app/event/dx/behaviors.py, plone/app/event/locales/fr/LC_MESSAGES/plone.app.event.po
- Do not index `sync_uid`, `start` and `end` fields if they are empty.
- Update french translations.
=>  bsuttor cherry picks from 1.1.x into master

CHANGES.rst, plone/app/event/recurrence.py, plone/app/event/tests/test_recurrence.py
currently on an event w/o recurrences accessing Plone/event/2017-11-29 leads to a stopiteration error
visitors get a site-error instead of the notfound page.
add test that for traversing to
* a valid date
* on an event w/o recurrences
to make sure an AttributeError is raised instead of the StopIteration
=> when traversing to not existend occurence, return a NotFound instead of a site error

CHANGES.rst, plone/app/event/browser/event_listing.py, plone/app/event/ical/exporter.py, plone/app/event/tests/test_event_listing.py, plone/app/event/tests/test_icalendar.py
Explicitly set the 'Content-Length' header when exporting events as ICS, to avoid issues like haproxy setting it to 0 under certain configurations
=> Make sure to include the 'Content-Length' header for ical exports

news/306.bugfix, plone/app/event/tests/test_ical_import.py
allowed_attributes and allowed_interfaces was broken in Zope 4.0 
See https://github.com/zopefoundation/Zope/issues/397
=> Add regression-test for allowed_attributes

news/2952.bugfix, plone/app/event/configure.zcml
This is for our use of the `plone:static` directive.
See https://github.com/plone/Products.CMFPlone/issues/2952
=> Load zcml of plone.resource.

news/3130.bugfix, plone/app/event/profiles/testing/types/plone.app.event.dx.event.xml, plone/app/event/testing.py, plone/app/event/tests/test_dx_behaviors.py, plone/app/event/tests/test_ical_import.py, plone/app/event/tests/test_recurrence.py
`plone.app.event` master is still used in Plone 5.1, so we fall back to the original `plone.testing.z2` there.
I think named behaviors already work in 5.1.
=> Fix deprecation warnings in tests: use plone.testing.zope and named behaviors.

news/3209.bugfix, plone/app/event/ical/importer.py
This could be a line of attack for a hacker.
But the hacker would already need to have Manager rights to see the resulting error, before getting some useful information from this.
See https://github.com/plone/Products.CMFPlone/issues/3209
=> Give validation error in ical importer when a file:// URL is used.

news/332.bugfix, plone/app/event/portlets/portlet_events.pt
See #332, plone/plone.app.contenttypes#486, and PR plone/plone.app.contenttypes#603).
This PR is against `3.2.x`, but the commit should merge cleanly against `master` and `3.x`.
=> Fix issue with events portlet rendering when thumbs disabled (#332)

news/3274.bugfix, plone/app/event/ical/importer.py, plone/app/event/tests/test_ical_import.py
Previously, only `file://` was disallowed, but this left room for relative paths.
Taken over from [PloneHotfix20210518](https://plone.org/security/hotfix/20210518/server-side-request-forgery-via-event-ical-url).
=> Do not allow file: protocol in ical url. [master]

news/3274.bugfix, plone/app/event/ical/importer.py, plone/app/event/tests/test_ical_import.py
Previously, only `file://` was disallowed, but this left room for relative paths.
Taken over from [PloneHotfix20210518](https://plone.org/security/hotfix/20210518/server-side-request-forgery-via-event-ical-url).
=> Do not allow file: protocol in ical url. [3.2.x]

news/261.bugfix, plone/app/event/base.py, plone/app/event/tests/test_base_module.py
expand_events returns the event items passed in `events` even if they do not fit into `start` and `end` (which are only used to limit the search for occurrences).
Previously events got removed if they did not fit into the start-end-range although the method is called `*expand*_events`.
(this fixes #261)
=> expand_events does not remove events

news/355-2.bugfix, news/355-3.bugfix, news/355.bugfix, plone/app/event/browser/resources/event.js
- Wrap JavaScript a immediately invoked function to not expose the functions in global namespace.
- Remove project-specific code from selectors in the event JavaScript.
- Do frontend date widget calculation with datetime-native dates to simplify code better universal support.
@petschki I used the plone.app.event script with your additions in a own project, but setting the end date based on the start date did not really work. Maybe I did integrate it incorrectly late at night, but in the end this is what I came up with. I think this is a simpler approach as it does not mess with timezones where we do explicitly not want timezones (datetime-native).
=> JavaScript improvements

news/450.bugfix, plone/app/event/tests/test_icalendar.py
There ``;VALUE=DATE-TIME`` is not included because it is already the default. See https://github.com/collective/icalendar/pull/450
=> Fixed tests to work with future icalendar.

news/367-pam.breaking, plone/app/event/dx/behaviors.py, setup.py
The plone.app.event IEventBasic fields are language independent. 
Move code to plone.app.multilingual to not depend on it.
Needs test/merge together with plone/plone.app.multilingual#414
=> Remove dependency on plone.app.multilingual.

news/362.bugfix, plone/app/event/recurrence.py
fixes #362 
screenshots with debug info `date_dict/iso_start - date_dict/iso_end`
Before:
After:
=> Event Occurrence `open_end` fix

CHANGES.rst, buildout.cfg, plone/app/event/browser/event_listing.py, plone/app/event/ical/exporter.py, plone/app/event/tests/test_event_listing.py, plone/app/event/tests/test_icalendar.py
This causes an empty iCal download when working with Varnish.
=> Fix missing Content-Length header when exporting iCal

news/172.internal, pyproject.toml, tox.ini
When built with setuptools 68.1, you could not import the package, at least not an editable package. Note that you can still *install* this package with older setuptools versions. See [Plone meta issue 172](https://github.com/plone/meta/issues/172) for details.
New problem though.  `tox -e dependencies` says:
```
ERROR Missing dependencies:
setuptools>=68.2
```
I tried with `setuptools<68.1', which would also work, but that only changes the message:
```
ERROR Missing dependencies:
setuptools<68.1
```
I think this is a shortcoming in `z3c.dependencychecker`.  It should not report this as a missing dependency. It should see that `pyproject.toml` has this dependency covered.
We definitely should *not* require `setuptools>=68.2` in `install_requires`.
=> Require setuptools 68.2 or higher for building the package.

news/334.tests, plone/app/event/tests/test_portlet_calendar.py
Fixes https://github.com/plone/plone.app.event/issues/334.
Screen shot of the rendered portlet (no css here) in the new test:
=> Fix test_long_event when run around midnight of first day of month

news/387.bugfix.md, plone/app/event/dx/behaviors.py, plone/app/event/tests/base_setup.py, plone/app/event/tests/test_portlet_events.py, setup.py
Eventaccessor urls are diffrent if the come from ram cache or not. in some enviroments the links are not accessible. This fix extends the url calculation.
=> Fix for #387 - Fix calculation of eventaccessor urls

news/393.bugfix, plone/app/event/ical/exporter.py, plone/app/event/tests/test_icalendar.py
Fixes #393 by not using our own `null` datetime, which was equal but not identical to `datetime.min`.
The test provided throws an OverflowError without the patch provided.
=> Don't error out on 'Africa/Abidjan' timezone [gyst]

news/399.bugfix, plone/app/event/portlets/portlet_calendar.py, plone/app/event/tests/test_portlet_calendar.py
=> Fix calendar portlet to work when selected item is a Collection

news/404.bugfix, plone/app/event/browser/event_listing.py, plone/app/event/tests/test_event_listing.py
fixes https://github.com/plone/Products.CMFPlone/issues/3959
=> Fix date conversion when collection context has start/end date queries

news/407.bugfix, plone/app/event/browser/event_summary.pt
If the name is None, display the mail. Otherwise, a person icon with no useful info is displayed.
=> Yurj link to mail if name none

news/6.bugfix, plone/app/event/__init__.py
The new `zoneinfo` support in `icalendar` 6 does not work for us yet, giving indexing problems. So we call `icalendar.use_pytz` at startup.
If this fails, we must be using an older version where `pytz` is the only option anyway, so we ignore this.
Locally, when I add calendar 6 in the Plone coredev 6.1 buildout, and run `bin/test -s plone.app.event -m test_icalendar` on this branch, those tests pass.
But let's first test if this is still fine in combination with icalendar 5.
=> Support icalendar 6 by forcing it to use pytz

news/415.bugfix, plone/app/event/dx/behaviors.py
For the start and end fields, do not explicitly define the DateTimeFieldWidget. This allows for easier customization when a different widget needs to be used for any DateTime field.
=> Relax DateTime widget definition.

news/+fix-plone-displayviews.bugfix.rst, plone/app/event/browser/configure.zcml, setup.py
Fix a problem where plone_displayviews could not be imported in a Plone 6.1, Python 3.12 project.
I love to make my live complicated and did depend directly on Products.CMFPlone, not Plone. That might be part of the problem. However, this PR fixes it.
I found the solution via the 12 year old bug report here: https://github.com/collective/collective.blog.view/issues/5 :heart: 
OK, as I just found out it can also be fixed by really depending on CMFPlone.
I forgot to add a
```
<include package="Products.CMFPlone" />
```
Anyways, explicit is better than implicit - I think this PR makes still sense as long as plone.app.events needs plone_displayviews.
Traceback:
```
File "/.../sources/plone.app.event/plone/app/event/browser/configure.zcml", line 16.2-25.8 …
```
=> Fix import problem for plone_displayview by explicitly depending on plone.app.content menu.

news/+stabilize-tests.internal.rst, plone/app/event/tests/test_portlet_calendar.py, plone/app/event/tests/test_portlet_events.py
At the end of a month the calendar test was failing due to some dates reaching
into the next month and not being rendered anymore in the current month.
This is now stabilized.
=> Stabilize tests
