CHANGES.rst
plone/app/event/browser/resources/event.js
plone/app/event/portlets/portlet_calendar.py
plone/app/event/portlets/portlet_events.py

Reverts plone/plone.app.event#195

Revert "removing dependency on p.a.contenttypes"

---

CHANGES.rst
plone/app/event/browser/resources/event.js
plone/app/event/portlets/portlet_calendar.py
plone/app/event/portlets/portlet_events.py

Reverts plone/plone.app.event#196
Original the same as #195

"removing dependency on p.a.contenttypes" second trial (Revert "Revert #195)

---

CHANGES.rst
plone/app/event/browser/event_listing.py

Fixes plone/Products.CMFPlone#1019.

Resolve deprecation warning for getDefaultPage.

---

plone/app/event/base.py
plone/app/event/recurrence.py

otherwise sphinx starts complaining when building docs.plone.org

docstrings need to be valid rst

---

CHANGES.rst
plone/app/event/portlets/portlet_events.pt
plone/app/event/portlets/portlet_events.py
plone/app/event/tests/test_portlet_events.py

see  https://github.com/plone/Products.CMFPlone/issues/1226

PR:show thumbs when leadimage behavior enabled for eventtype:

---

CHANGES.rst
plone/app/event/tests/base_setup.py
plone/app/event/tests/test_event_listing.py

Should be merged together with pull requests in other packages.
Central issue: https://github.com/plone/Products.CMFPlone/issues/1040

In tests, use ``selection.any`` in querystrings.

---

CHANGES.rst
plone/app/event/browser/resources/event.css

Reverts plone/plone.app.event#218

Revert "index1445-calendarwidget"

---

plone/app/event/locales/ru/LC_MESSAGES/plone.app.event.po
plone/app/event/locales/ru/LC_MESSAGES/plone.po

added files with the translation into Russian

Patch 1 - added files with the translation into Russian

---

CHANGES.rst
plone/app/event/dx/configure.zcml

short-names for behaviors

---

CHANGES.rst
plone/app/event/portlets/portlet_calendar.py
plone/app/event/tests/test_portlet_calendar.py

fgrcon tooltip fix backport from master

---

CHANGES.rst
plone/app/event/dx/behaviors.py
plone/app/event/recurrence.py
plone/app/event/tests/test_recurrence.py

Fixes: https://github.com/plone/plone.app.event/issues/185

Fix views should show the next upcoming recurrence of event.

---

plone/app/event/portlets/portlet_events.pt
plone/app/event/portlets/portlet_events.py

Followup of https://github.com/plone/Products.CMFPlone/issues/1734

Cleanup of PLIP #1734

---

CHANGES.rst
plone/app/event/browser/resources/event.css
plone/app/event/browser/resources/event.js

Improve the JavaScript to wait for the PickADate pattern to be initialized.
Follow better JS practices.
Merge all these:
https://github.com/plone/Products.CMFPlone/pull/2132
https://github.com/plone/plone.app.event/pull/260

JS Initialization fixes, JS Code improvement

---

CHANGES.rst
plone/app/event/base.py
plone/app/event/portlets/__init__.py

This fixes #271 but maybe someone wants to give this a review first...

fallback search base url for portlets to NavigationRoot

---

CHANGES.rst
plone/app/event/locales/da/LC_MESSAGES/plone.app.event.po
plone/app/event/locales/da/LC_MESSAGES/plone.po
plone/app/event/portlets/__init__.py

cherrypicks

---

news/298.feature
plone/app/event/browser/configure.zcml

After that, we need to update also p.a.locales..what's the policy for doing this?

Translate event listing name

---

news/302.bugfix
plone/app/event/dx/behaviors.py
plone/app/event/tests/base_setup.py
plone/app/event/tests/test_search.py

fix SearchableText indexer for Python 3

---

news/312.bugfix
plone/app/event/browser/event_listing.pt
plone/app/event/browser/event_summary.pt
plone/app/event/browser/event_view.pt

- changed in event_listing.pt
- changed in event_summary.pt
- changed in event_view.pt

Change markup for structured data schemas

---

news/326.breaking
plone/app/event/browser/event_listing.pt

- add BS5 compatible Nav structure for Upcoming/Past/iCal Navigation

Update Markup event_listing.pt

---

news/261.bugfix
plone/app/event/base.py
plone/app/event/tests/test_base_module.py

this is a follow up of  #262 for the 3.2.x branch (currently used for plone 5.2) that also adds a small test with explanation what the change is good for.
this fixes https://github.com/plone/plone.app.event/issues/261

fix epand_events for future events 

---

news/350.bugfix
plone/app/event/browser/resources/event.js
plone/app/event/profiles/default/metadata.xml
plone/app/event/profiles/default/registry.xml

Update event.js and remove plone-legacy bundle

---

news/2780.feature
plone/app/event/dx/behaviors.py
plone/app/event/dx/configure.zcml
plone/app/event/profiles/testing/types/plone.app.event.dx.event.xml

PLIP https://github.com/plone/Products.CMFPlone/issues/2780

Disable searchable_text_indexer (is now covered by p.a.d.textindexer)

---

news/348.bugfix
plone/app/event/base.py

Fixes doubled first occurrence of recurring event

---

.meta.toml
news/0b0246aa.internal
pyproject.toml
setup.py

Fixes https://github.com/plone/plone.app.event/issues/373

Re-add Products.DateRecurringIndex dependency.

---

news/376.bugfix
plone/app/event/browser/resources/event.js

When installing with `collective.z3cform.datagridfield` in Plone 4.3 there's a conflict with the redefined `require` here.

Fix conflicts with `require` in other packages [2.0.x]

---

.gitignore
.meta.toml
.pre-commit-config.yaml
tox.ini

_Remember to use `[ci-skip]` on the merge commit message to avoid spamming Jenkins_ ✨ ♻️

Configuring with plone/meta

---

news/408.feature
plone/app/event/testing.py
plone/app/event/tests/robot/test_event_roundtrip.robot
plone/app/event/tests/robot/variables.py
plone/app/event/tests/test_robot.py

This is part of https://github.com/plone/Products.CMFPlone/issues/3813
Fix for #408

Playwright based robot test
